from NormReferenceGroup import NormReferenceGroup

# some default values for parameters - to be overwritten by props file
BETA_ATTITUDE = 1.0/3.0
BETA_NORM = 1.0/3.0
BETA_PBC = 1.0/3.0
BETA_RESTRAINT = 0.1
BETA_EMOTIONAL = 1
BETA_PD = 0.5
BETA_HFSSBMIVAL = 0.5
BETA_BMIVALPD = 0.5
BETA_BMIVALEMO = 0.5
BETA_INTERVENTIONEFFECT = 0.5
BETA_INTERVENTIONSCALE = 0.5
BETA_ATTITUDEALPHA = 0.5
BETA_PDALPHA = 0.5
BETA_BMIALPHA = 0.5

MALE = "m"
FEMALE = "f"

AGENT_LEVEL_OUTPUT = False

P_REFERENCE_GROUP = None
NUM_SEX = 2
NUM_SES = 3
NUM_SCHEMA = 5

MAX_AGE = 80
AGE_GROUPS = [16, 35, 46, 65, MAX_AGE]
NUM_AGE_GROUPS = len(AGE_GROUPS) 

P_REFERENCE_GROUP = NormReferenceGroup()
